always_save_checkpoint: false
backend: nccl
batch_size: 256
beta1: 0.9
beta2: 0.99
bias: false
block_size: 256
ckpt_path_name: ckpt_10000.pt
compile: true
data_format: eval_format
data_type: text
dataset: bal
decay_lr: true
device: cuda:0
dropout: 0.2
dtype: bfloat16
eval_addition: true
eval_interval: 250
eval_iters: 200
eval_judge: false
eval_only: false
exp_name: add-only-10000-eval-form
grad_clip: 1.0
gradient_accumulation_steps: 1
init_from: scratch
judge: false
judge_mode: bilabel
judge_start: null
learning_rate: 0.001
log_interval: 10
lr_decay_iters: 5000
max_iters: 5000
meta_path_specified: true
min_lr: 6.0e-05
n_embd: 384
n_head: 6
n_layer: 6
operator: +
out_dir: out-check-add-only-eval-form
result_dir: out-check-add-only-eval-form/add-only-10000-eval-form
resume_from: null
reverse_c: false
start: FILE:data/bal/test_3digit_10000.txt
tokenizer: char
train_data_path: train_3digit_10000.txt
val_data_path: val.bin
vocabulary: all_ascii_chars
wandb_log: true
wandb_project: addition
wandb_run_name: add-only-10000-eval-form
warmup_iters: 100
weight_decay: 0.1
