always_save_checkpoint: false
backend: nccl
batch_size: 256
beta1: 0.9
beta2: 0.99
bias: false
block_size: 256
ckpt_path_name: ckpt_10000.pt
compile: true
data_format: reverse
data_type: text
dataset: bal
decay_lr: true
device: cuda:0
dropout: 0.2
dtype: bfloat16
eval_addition: true
eval_addition_train: true
eval_interval: 250
eval_iters: 200
eval_only: false
exp_name: add-bal-rev_10000
grad_clip: 1.0
gradient_accumulation_steps: 1
init_from: scratch
judge: false
learning_rate: 0.001
log_interval: 10
lr_decay_iters: 5000
max_iters: 5000
min_lr: 6.0e-05
n_embd: 384
n_head: 6
n_layer: 6
operator: +
out_dir: out-check-new-rev
result_dir: out-check-new-rev/add-bal-rev_10000_4
reverse_c: true
start: FILE:data/bal/test_3digit_10000.txt
tokenizer: char
train_data_path: train_3digit_10000.txt
val_data_path: val.bin
vocabulary: all_ascii_chars
wandb_log: true
wandb_project: addition
wandb_run_name: add-bal-rev_10000
warmup_iters: 100
weight_decay: 0.1
